const memories = [
    "It was a beautiful, warm, blue sky day. Sitting on a bench by the bridge on the canal, we'd walked a good amount, I just wanted to sit there, watch the water and cuddle you. But you insisted, gave me '5 more minutes' before grabbing me to keep walking down the canal, I felt like a total fatass ;[",
    "It was another beautiful day, perhaps my memory isn't too good because I feel as though a lot of the days we spent together were clear skies. Maybe it's just the Manel effect, regardless, we were walking down bank street, a big, red, OC transpo bus came whirling by and you started singing 'aaaaaand ifff a douuublleee deccckeerrr busss crasssheesss intooo usss ♪'. I had no clue what you were on about and I honestly forgot that memory until you brought it up, so I guess you're kind of my little memory book <3",
    "Staring & daydreaming at you in class, you're really really pretty and just give a warm feeling in my heart when my eyes see you 💗",
    "This memory is a little different, it was a dream I had written down the moment I wokeup right before school, in October, I read the paper enough times to the point I remember it so clearly. I kept those words for a few months, and when I decided to give it to you... well the timing was wrong, and I lost the paper (kind of like that really nice bracelet you got me 😥). Regardless, the dream went like this: It was you, sitting on one of the tall blue foyer chairs, laughing, giggling, as I just stared in utter admiration. We were inside a white, endless room. I sort of just watched you from afar in the dream, and suddenly, you got up off the chair and kind of rolly-pollied over to me, trying to hug me. I pushed you off for a moment, but gave in rather quickly. I tried to kiss you, you put your finger on my mouth and said 'not until I fix things'. That hug, even though it was just a dream, made me so happy, waking up was honestly the worst part, if I could go back to that moment in my head in a heartbeat I would, I was more than happy with you, right then and there 😊",
    "Walking through the park near the school after driving over during an empty philo hour… it was refreshing to say the least. I can almost remember your smile that day, walking around the streets and gardens was just so nice, balancing on the beams near the parking lot, a fondest memory <3",
    "I think it was a Friday morning. I didn’t have my first hour of cours and so I had planned to walk to a nearby flower shop to buy you flowers to ask you to be my gf. I got to school, made a little heart paper envelope, took a chilly walk to the store where the girl who helped me with the flowers especially told me not to shove them in my bag (I was really nervous idk being seen holding flowers is scary). I sorta realized I miscalculated the time and I was going to lose 10 minutes of time with you from the walk back too which I kiiinda really wanted to spend but my heart was racing so fast all morning I wasn’t sure what to think so it was fine. I walked up to the library where you were with your friend Maane, except I didn’t see you instantly and wound up circling around the library once super red n flustered. When I finally found you, I can still remember the “oh mai gawsh” in your voice… you looked so damn pretty (still do!). And obviously I was over the mooooon when you said yes down by the lockers after a walk which felt like a teleportation, idk how to explain it but there’s happiness and then there was THAT feeling, ily and the memories 😊💌",
    "Kissing you anywhere anytime… you have the softest & sweetest lips (not that I would know what others taste like but yours are definitely the best ones!), if I had to give my specific for personal favourite, standing up while kissing might be the best coz you can lean into it more (??? I don't know if that makes sense, but cuddling is def wayy better laying down, but kissing on park benches was also 🌟)",
    ""
]

function selectMemory () {
    const random_memory = memories[Math.floor(Math.random() * memories.length)] 
    document.getElementById("memoryDisplay").textContent = random_memory
}